# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gantt_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField()),
                ('target', models.IntegerField()),
                ('type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gantt_tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('progress', models.FloatField()),
                ('sortorder', models.IntegerField()),
                ('parent', models.IntegerField()),
            ],
        ),
    ]
