# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantt_tasks',
            name='end_date',
            field=models.DateTimeField(default='2016-04-06 00:00:00'),
        ),
        migrations.AlterField(
            model_name='gantt_tasks',
            name='progress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gantt_tasks',
            name='sortorder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
