# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0002_auto_20160916_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gantt_tasks',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
